fix: update release tag pattern and enhance release task with version argument check (#10)

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -81,6 +81,17 @@ tasks:
       - test -f ./updater/artifacts/resources_windows_amd64/qdl.exe
     cmd: sh ./updater/artifacts/download_resources.sh
 
+  release:
+    desc: Create a tag on the current commit and push it to the remote to create the release
+    cmds:
+      - |
+          if [ -z "{{.CLI_ARGS}}" ]; then
+            echo "Error: Version argument is required. Usage: task release -- <version>"
+            exit 1
+          fi
+      - git tag -a "{{.CLI_ARGS}}" -m "Release {{.CLI_ARGS}}"
+      - git push origin "{{.CLI_ARGS}}"
+
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-dependencies-task/Taskfile.yml
   general:cache-dep-licenses:
     desc: Cache dependency license metadata
